# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bnymdemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BYNMdemo(object):
    def setupUi(self, BYNMdemo):
        BYNMdemo.setObjectName("BYNMdemo")
        BYNMdemo.resize(236, 276)
        self.centralwidget = QtWidgets.QWidget(BYNMdemo)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_go = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_go.setObjectName("bt_go")
        self.horizontalLayout.addWidget(self.bt_go)
        self.bt_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_stop.setObjectName("bt_stop")
        self.horizontalLayout.addWidget(self.bt_stop)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 130, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab_enter_something = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lab_enter_something.setObjectName("lab_enter_something")
        self.verticalLayout.addWidget(self.lab_enter_something)
        self.le_something = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_something.setObjectName("le_something")
        self.verticalLayout.addWidget(self.le_something)
        BYNMdemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BYNMdemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 236, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        BYNMdemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BYNMdemo)
        self.statusbar.setObjectName("statusbar")
        BYNMdemo.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(BYNMdemo)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(BYNMdemo)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(BYNMdemo)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit_2 = QtWidgets.QAction(BYNMdemo)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(BYNMdemo)
        self.actionQuit_2.triggered.connect(BYNMdemo.close)
        QtCore.QMetaObject.connectSlotsByName(BYNMdemo)

    def retranslateUi(self, BYNMdemo):
        _translate = QtCore.QCoreApplication.translate
        BYNMdemo.setWindowTitle(_translate("BYNMdemo", "BYNM Demo"))
        self.bt_go.setText(_translate("BYNMdemo", "Go"))
        self.bt_stop.setText(_translate("BYNMdemo", "Stop"))
        self.lab_enter_something.setText(_translate("BYNMdemo", "Enter something "))
        self.menuFile.setTitle(_translate("BYNMdemo", "File"))
        self.actionQuit.setText(_translate("BYNMdemo", "Quit"))
        self.actionOpen.setText(_translate("BYNMdemo", "Open..."))
        self.actionSave.setText(_translate("BYNMdemo", "Save..."))
        self.actionQuit_2.setText(_translate("BYNMdemo", "Quit"))
